apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-deployment
spec:
  selector:
    matchLabels:
      app: mosquitto-broker
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: mosquitto-broker
    spec:
      containers:
      - name: mosquitto-broker
        image: alanjian131/hw2-local-broker:v1
        ports:
        - containerPort: 1883
