apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-detector-deployment
spec:
  selector:
    matchLabels:
      app: mosquitto
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: face-detector
        image: alanjian131/hw2-face-detector:v1
        ports:
          - containerPort: 1883
