apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-detector-deployment
spec:
  selector:
    matchLabels:
      app: mosquitto
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      hostNetwork: true
      containers:
      - name: face-detector
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
        env:
        - name: DISPLAY
          value: /dev/video0
        securityContext:
          privileged: true
        image: alanjian131/hw2-face-detector:v1
        ports:
          - containerPort: 1883
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0

